# -*- coding: utf-8 -*-
"""Let's code loops 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LEgmGYtbxsKqjTxXj4sVQqZ6xyKiHiI0

Task 2
"""

# Python program to print positive Numbers in a List
  
# list of numbers
list1 = [12, -7, 5, 64, -14]
  
# iterating each number in list
for num in list1:
      
    # checking condition
    if num >= 0:
       print(num, end = " ")

# list of numbers
list2 = [12, 14, -95, 3]
  
# iterating each number in list
for num in list2:
      
    # checking condition
    if num >= 0:
       print(num, end = " ")